export const OK_STATUS = 200;
export const DEVCON_FETCH_JOB_PREFIX = "DEVCON_FETCH_JOB";
export const PRETALX_FETCH_JOB_PREFIX = "PRETALX_FETCH_JOB";
export const DEVCON_FEED_TOPIC_PREFIX = "DEVCON";
export const PRETALX_FEED_TOPIC_PREFIX = "PRETALX";
